### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by sunny-gg95** [paulevsGitch/BetterEnd#186]
https://drive.google.com/file/d/1lATbDd5Eoh-FUImNSrNhVzQEp3WTSAVP/view?usp=sharing

what should I do

**Comment by paulevsGitch** [comment]
> what should I do

- First of all - correctly create issue, with right name (for example "Player stuck in the portal Bedrock after teleportation" instead of "what?")
- Second - proper description ("After teleport into the End with installed immersive portals player stuck in the bedrock as te portal is not placed before player teleports" instead of "what should I do")

As a result - this is a vanilla behaviour. End portal is placing after dragon spawning. In vanilla spawn point is far away from it and this doesn't cause any issues. Your spawn point is directly above portal and you jumped into it right after it created before dragon spawned and portal placed. There is no issue on BE side. What you should do? The simplest answer - wait before portal spawns. More complex answer - somehow make portal open after portal creation or not in the center of the End
