### ISSUE TITLE
better-end-0.9.8.5 crashing alongside Eldritch mobs (old version didn't)

### ISSUE THREAD

**Issue by githubbingitup** [paulevsGitch/BetterEnd#214]
MC 1.16.5.
Latest versions of Fabric API, Eldritch, and Better End.

The old version better-end-0.9.6-pre didn't crash when used with Eldritch, so I figured I'd report it here. Seems to be related to a blindness attribute.

Here's the crash log. Lots of mods are being used, but the crash details seem to only relate to BetterEnd and Eldritch. Downgrading to version better-end-0.9.6-pre fixed the problem for me.
[eldrich.txt](https://github.com/paulevsGitch/BetterEnd/files/6719431/eldrich.txt)

**Comment by Bulldog83** [comment]
It's incompatibility with [PlayerEx](https://www.curseforge.com/minecraft/mc-mods/playerex) mod. It [compleately rewrites](https://github.com/CleverNucleus/PlayerEx/blob/master/src/main/java/com/github/clevernucleus/playerex/mixin/LivingEntityMixin.java) player attributes with it's own.

**Comment by CleverNucleus** [comment]
Hi there,
The issue is due to the attribute `betterend:generic.blindness_resistance` missing its json file when running with PlayerEx. PlayerEx exposes player (PlayerEntity) attributes as json's allowing for datadriven attributes and datapack support. The tradeoff for lazy-loading player attributes is that if the relevant json file is missing, the attribute (even if it's registered) does not get added to the player's attribute container. 

The fix is simple: _somewhere_ there must exist `data/betterend/attributes/generic.blindness_resistance.json` (following the json format guidelines discussed [here](https://github.com/CleverNucleus/PlayerEx/wiki/JSON-Format)).

The json can be added by:
 - myself, which could be included in PlayerEx by default in the next release; this would result in the player having this attribute, but it would only ever get used when BetterEnd is installed.
 - BetterEnd could include this json in its next release; without PlayerEx installed this would of course be a meaningless file that would do nothing except contribute compatibility with PlayerEx.
 - The end user could add this json via a datapack, which is what I advise on my mod page.

I believe that is all that's needed to fix the issue, and I hope that this is of some use,
Thanks.

**Comment by paulevsGitch** [comment]
The latest version shouldn't crash, Json will be added later
