### ISSUE TITLE
[compatibility] [bluemap] Certain Blocks do not work with Bluemap

### ISSUE THREAD

**Issue by Merith-TK** [paulevsGitch/BetterEnd#266]
BE 9.8.5, MC 1.16.5, Fabric
These Blocks show up as missing textures in Bluemap
* Dragon Tree Leaves, 
* Dragon Bone Blocks (all varieties)
* Lanterns 

Bluemap devs believe it to be because BE uses custom rendering code for these block's models, making it incompatible with bluemap

![image](https://user-images.githubusercontent.com/10422110/127747004-06843836-2860-45cd-83dd-a0feaf2b3784.png)

poked around the mod's assets and it appears that all the blocks that are having issues are ones without an entry in the models folder

**Comment by Merith-TK** [comment]
Even a stopgap fix such as providing a resource pack for blue map specifically to properly render these blocks would be helpful at the very least

**Comment by paulevsGitch** [comment]
BetterEnd don’t have custom rendering for these blocks, they use same pattern system as all other BE blocks

**Comment by Merith-TK** [comment]
Well, I am only seeing it occur with BE blocks, while other modded blocks work just fine,

**Comment by Merith-TK** [comment]
So it suggests there is an issue with BE and how these block textures are registered in general.

**Comment by paulevsGitch** [comment]
Well, if Bluemap operates only with stored JSON it will be impossible to fix, sorry. All models for blocks will be available in Model Bakery like all other models

**Comment by Merith-TK** [comment]
Well, feel free to pin this one for people who use bluemap

**Comment by Merith-TK** [comment]
Please ignore fekked world gen, we screwed with it and it was probably incompatibilities with other mods at the time

![image](https://user-images.githubusercontent.com/10422110/127756830-c065a960-60e2-413a-9c29-ef13b943d225.png)
![image](https://user-images.githubusercontent.com/10422110/127756842-d37ce34b-6674-4e05-a603-4ff8709af27a.png)
![image](https://user-images.githubusercontent.com/10422110/127756880-e1beb1de-d5d8-4c62-8bf3-3a65eaa58b2b.png)
![image](https://user-images.githubusercontent.com/10422110/127756893-1729ba25-8d8d-45b7-87e5-cd8e36b443c9.png)
![image](https://user-images.githubusercontent.com/10422110/127756917-77577690-2dae-43f6-8da6-6d9bff6a4b6e.png)
![image](https://user-images.githubusercontent.com/10422110/127756931-d16d8537-268e-4c2e-a743-f2feadef119c.png)

**Comment by Merith-TK** [comment]
One of the people I talk to suggests making "dummy files" that are *placeholders* for things that require it, while the mod itself doesn't necessarily require it, just for compatibility, 

Like dont convert the mod to use blockstate model json's, just include unused ones for mods that do require it for things,

**Comment by Merith-TK** [comment]
> All models for blocks will be available in Model Bakery like all other models

Could you elaborate on what the Model Bakery is? Im trying to find information or where it could be but have no results on google, bing, or even *yahoo*

**Comment by paulevsGitch** [comment]
> Could you elaborate on what the Model Bakery is

It is minecraft model storage that is used by the game to operate with models. Jsons are raw models that are loaded into bakery, MC itself uses only model bakery. I think Bluemap doesn't use it as it is not available on server side

> suggests making "dummy files"

At this moment it is impossible, if there is a Json for blockstate - it will replace automatic blockstate. This used for some block model changing (and these blocks are visible on Bluemap) and for resourcepack makers

**Comment by Merith-TK** [comment]
If mc used this "model bakery", which I *still can't find anything about* so I'm assuming your talking about **baked models** which MC doesnt use anywhere to my knowledge, and practically everyone I have talked to for fabric modding says is not a good idea to use baked models

Not even `adorn` uses baked models, and they have an legit reason to because of their complete geometry 

How does the "automatic blockstate" differ from normal blocks doing things in general when something is placed next to it.

And where does model baking take place in the build process? IE, where in the code does this take place so I can look at it and understand what it is doing.

**Comment by paulevsGitch** [comment]
> your talking about baked models which MC doesnt use anywhere to my knowledge

Baked models is the *only one* way of MC to load and render block models, Fabric model API is mostly a set of wrappers around vanilla Bakery and its models, both Fabric and MC models are equal, except Fabric models have more options

> And baking models is a different way of rendering a block, which you specifically said that BE doesn't use anything special to render blocks.

It is a *vanilla* way of rendering blocks. All jsons are loaded in Model Bakery (blockstates, items and blocks) and transformed into Unbaked models. BE use BCLib json loader and provide unbaked models *directly* into bakery instead of loading a set of json for each block, which in terms of game rendering has no difference, it is only a bit *different way of loading*

> all BE blocks should not work

As I said earlier:

> if there is a Json for blockstate - it will replace automatic blockstate. **This used for some block model changing (and these blocks are visible on Bluemap)**

> Not even adorn uses baked models, and they have an legit reason to because of their complete geometry

As MC uses them - it is not true. It is not depending on how models are created outside of MC - json models, obj geometry or whatever, inside MC *all* models will become UnbakedModels and then they will be baked, as this is the only one way to render blocks in chunks for MC. Model makery provides textures to model, form their quads, parse materials, apply transformations and do all other things related to block models.

> How does the "automatic blockstate" differ from normal blocks doing things in general when something is placed next to it.

With loading process. Instead of manually adding thousands of thousands lines for each json file it is done automatically in code. For MC itself there is no difference.

Block & Utem models just use *patterns* - single JSON file for all blocks of this type with automatic texture replacement instead of manually made files, except some blocks that requires different rendering - they have all ordinal JSON files, and again - they are loaded by Bluemap as their models exists

> And where does model baking take place in the build process? IE, where in the code does this take place so I can look at it and understand what it is doing.

It happens on resource reload, for example [here](https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/client/ModelBakeryMixin.java) is BCLib custom model loader (v.0.3.0, after some modifications, it may be different from 0.2.4)

**Comment by FrostBird347** [comment]
Since I have been experiencing this issue with both BlueMap and PolyMc, I have started making the 'missing' JSON files myself.
I can't guarantee that I will be able to finish it within the next few weeks, but it is available [here](https://github.com/FrostBird347/BetterEnd-Resource-Fix).
