### ISSUE TITLE
Disconnect when loading into a new singleplayer world on Betterend latest ver (Mod conflict?)

### ISSUE THREAD

**Issue by Alkiasan** [paulevsGitch/BetterEnd#374]
Latest.log:
https://pastebin.com/vnVVkXvJ

Removed various mods that seemed to be contributing without success. Worlds are creatable just fine without betterend, but having betterend with these mods seems to cause issues.

Removing Minegate, and Adorn/AdditionalAdditions seems to stop the issue, however, running them individually with Betterend seems to not cause the issue to re-occur, so it may be multiple mods/a particular mixin.

Reloading the corrupted world seems to cause it to get stuck at 83%.
Log:
https://pastebin.com/BFceJVmq

World file:
[New loop (39).zip](https://github.com/paulevsGitch/BetterEnd/files/7791837/New.loop.39.zip)

**Comment by Alkiasan** [comment]
New longer error upon reloading the world
https://pastebin.com/btA0Lw6t
Still testing with removing mods, removing Blockus also seems to fix the issue for some reason, but having individually blockus/betterend does not recreate it.

**Comment by dandin87** [comment]
[06:55:35] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "fabric:registry/sync"
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097176bytes where max allowed: 2097152
This issue should be fixed with Latest FAPI 0.45.1 which merged Registry sync packet compression II #1853
https://github.com/FabricMC/fabric/pull/1853

**Comment by quiqueck** [comment]
Did updating fabric API resolve this issue?

**Comment by Alkiasan** [comment]
Seems to fix the issue, yeah. I'll close the issue
