### ISSUE TITLE
 Custom shulker end ship datapack replacement doesn't work. Better end conflicts with terraforged. Both on forge.

### ISSUE THREAD

**Issue by JustReg2Download** [paulevsGitch/BetterEnd#78]
When I use datapack to replace old end ship,  it corrupts and has missing blocks.
I did report on terraforged mod page however they said that both two errors are not their fault.
They said that terraforged doesn't even change end generation.
Ship issue with screenshots and evidence.
https://github.com/TerraForged/tracker/issues/4

Terraforged creator also said same about world gen issue.
He explained that biome didn't generate because creator didn't make support for terraforged.
I tried energetic expansion on forge with terraforged with same version for forge.
And it worked.
Evidence with his screenshots and explanation.
https://github.com/TerraForged/tracker/issues/3
Please fix it.
P.s. Version 1.16.4 forge.

**Comment by JustReg2Download** [comment]
P.S. Version 1.16.4

**Comment by paulevsGitch** [comment]
This is Fabric version, all Forge issues need to be reported to Forge version tracker

**Comment by Beethoven92** [comment]
Why do i lose time to write changelogs and informations on the mod page if people don't read them :/ ? It is clearly stated that support for Terraforged was added in BetterEnd 1.4.0 changelog, and there is a compatiblity section on the mod page you should read. Please, the next time report issue on the BetterEnd issue page, not on other mods one, unless you absolutely sure that the issue is coming from their side. Here there was no reason to think that the datapack structure not creating properly was an issue with terraforged, and the explanation is very simple. The datapack was made for Fabric, in Forge we used a different mod id and so modded blocks registered with Fabric mod id were not recognized
