### ISSUE TITLE
Why is this mod overriding vanilla textures with no option to disable then?

### ISSUE THREAD

**Issue by ridjack** [paulevsGitch/BetterEnd#93]
As title. This is a not a good practice and creates inconsistencies with mods that rightfully assume Purpur will be using the vanilla texture.

If you're going to insist on replacing vanilla textures with your own, please have a config option to revert to vanilla.

**Comment by paulevsGitch** [comment]
- Why? By design
- How to disable? Use vanilla resourcepack

![2021-02-15_09 12 52](https://user-images.githubusercontent.com/17707380/107911704-1b4c4100-6f6e-11eb-8168-d886afaa1ac0.png)
![2021-02-15_09 12 56](https://user-images.githubusercontent.com/17707380/107911708-1dae9b00-6f6e-11eb-8af4-2e8d50953105.png)
![2021-02-15_09 12 58](https://user-images.githubusercontent.com/17707380/107911712-20a98b80-6f6e-11eb-8447-8440cc76e82d.png)
![2021-02-15_09 13 10](https://user-images.githubusercontent.com/17707380/107911716-22734f00-6f6e-11eb-8435-3bb2af021ef2.png)
